  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../user-service/applications/app-service/build/libs/user-service.jar:/app/user-service.jar
    depends_on:
      - auth-db
    networks:
      - crediya-net

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./loan-service/applications/app-service/build/libs/loan-service.jar:/app/loan-service.jar
    depends_on:
      - loan-db
      - user-service
    networks:
      - crediya-net
