version: "3.9"

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: crediya
      POSTGRES_PASSWORD: crediya
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - crediya-net

  loan-db:
    image: postgres:15
    container_name: loan-db
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: crediya
      POSTGRES_PASSWORD: crediya
    ports:
      - "5434:5432"
    volumes:
      - loan-db-data:/var/lib/postgresql/data
      - ./db/create_db_loan.sql:/docker-entrypoint-initdb.d/create_db_loan.sql
    networks:
      - crediya-net

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-db
    networks:
      - crediya-net

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    container_name: loan-service
    ports:
      - "8081:8081"
    depends_on:
      - loan-db
      - user-service
    networks:
      - crediya-net

volumes:
  auth-db-data:
  loan-db-data:

networks:
  crediya-net:
    driver: bridge
