server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: loan-service
  r2dbc:
    url: r2dbc:postgresql://loan-db:5432/loan_db
    username: crediya
    password: crediya

adapters:
  r2dbc:
    host: "loan-db"
    port: 5432
    database: "loan_db"
    schema: public
    username: "crediya"
    password: "crediya"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true

# Comunicación con user-service (usar el nombre del servicio en Docker Compose)
external:
  user-service:
    url: http://user-service:8080

security:
  jwt:
    secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo1Njc4OTAxMjM0NTY3ODkwMTIzNDU2
    expiration: 3600000
